$ANSIBLE_VAULT;1.1;AES256
61643434373837626465373137306463353163636561373735323436303465326262353665363766
3633376563363964353139343066363464643135393938350a623432313466666265346230353632
31396632323834383163623936643261656539316638313839353338323834306332663564336631
3730366265316362350a343937373632653539376436653463356264323637653561623931336339
64323934373932366239353336323364643235613536393135613735333635386162623365316361
61663065663436363639366161363132623062386462383933386434633839336237336339356637
61343163303561306630306639323530633333643961336236663331343433356230366137616633
65636566353663623930
