$ANSIBLE_VAULT;1.1;AES256
39373261653233643530646462313163333935343235616663633435366464363930313131356430
6530663430633739623932616561646666663630306634620a633638363737633464376534386665
61343730643636626238336539326665376532353335376632303233323933366136383937326632
3939643966663462630a306434623731616235666262333164323462323337666237306436373034
34636138623836653933663938376536323631343537616334663562383635656534633235313263
34323061346234396131363863636238343037663263663466616165633235646434663536336466
39653830393533323239653733666333646663316463313933313866666237393837383064316566
64636235663866363131353537633639346437653166613834383734613164343834663436646535
31653063613265373235663832373164366434386335306535303838393961353561663132643762
35316264386137626261346535616633656132326362356630633138313235326534303934323232
36643735663963376366616531333031346130643133333131626437393562666635356336656130
39333162633137326461373465336463376664373663376233633734643233373934383838356235
32363239326434383833616132373135643162653033653232313836633062643362333366643738
61363961323064656264663663656130616237316330393034386563636266353864623565343961
34656630373838326133366635663266343231323466306332633832366136643362336237653632
34323038343862663236613964303566636235366436383863353061626531646137653835303837
36663966383966623162316363326538666331396335343564326262386431383734323964343937
36656465623637363539663232316638326163313737383362633465656536326638666233623033
32366263316134626365343965313038633630333434636431333863646438363662643830616466
63333437356530336331363733353131313930613936666363663639346262326465343435636562
66343236623362656665366237323433326464356633333366313135333362656135663131643431
62613239353832613062336131643036373464626334343264306462396437633962663333313131
33663838666536353331626561326566336239323432363162633235666630373533666438616633
62666462333361373839353961316665313161353035356266323361333363626366336366356365
30383532663339313230383763663161636430316163393438383335653364383830643937316233
33363136336362616437333530363133663865373432663532386561316338663738633031333663
63386663626564373730633264346362333837356432663435613735333437313963316666393531
63363032333864366133663866356138306231333735353164393139666634653336656532326637
32623836323835626532373936643464633132613438646634386430643965666439323732613463
34343235623434663939663636616164313834663735343736666365373237666530613061623435
37653830346631343462326631313265306538373966316465393932633362306536313464613165
65346664303039323935
